/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DataStructures;

import DataStructures.LinkedList.LinkedList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
            LinkedList listy = new LinkedList();
            listy.addToFront(2);
            listy.addToFront(3);
            listy.addToFront(4);
            listy.addToEnd(7);
            listy.addAfter(2,28);
            System.out.println(listy);
            listy.removeFromEnd();
            System.out.println(listy);
        }
    }

